### ISSUE TITLE
未命名

### ISSUE THREAD

**Issue by WanderMax** [redomCL/mpv_fruit#1]
mpv讨论相关

**Comment by redomCL** [comment]
我是基于包括但不限于已经相对更加复杂的mpv_lazy等项目做的重组，本身并没贡献额外有用代码，如果发现我的配置出现配置相关问题可以在本项目反馈，其余mpv问题建议反馈到mpv官方或者移步mpv_lazy讨论板块讨论，此处不闲聊，我也没有能力帮助解决问题。相关链接可见本项目wiki
