### ISSUE TITLE
希望添加倍数播放

### ISSUE THREAD

**Issue by Sagittarius16th** [redomCL/mpv_fruit#2]
RT

**Comment by redomCL** [comment]
本项目几乎不会考虑增加倍速功能，本项目下只需要在input.conf里增加对应按键即可使用该功能，比如定义为按m按键倍速到x2，写入m set speed 2.0即可。
该功能mpv官方内置，官方默认快捷键已经包含。

**Comment by Sagittarius16th** [comment]
> 本项目几乎不会考虑增加倍速功能，本项目下只需要在input.conf里增加对应按键即可使用该功能，比如定义为按m按键倍速到x2，写入m set speed 2.0即可。 该功能mpv官方内置，官方默认快捷键已经包含。

好的，因为我是刚接触的，MVP官方定义还没弄清楚，就选择了你，/笔芯

**Comment by redomCL** [comment]
已添加倍速
